/** Directory containing all code generated by Honcho */
export const GENERATED_CODE_DIR = `${process.cwd()}/@honcho/generated`
/** Directory containing user-defined resources */
export const USER_RESOURCES_DIR = `${process.cwd()}/resources`
/** Glob of all user-defined resources */
export const USER_RESOURCES_GLOB = `${USER_RESOURCES_DIR}/*.{ts,tsx}`
/** Directory containing Honcho-generated resources */
export const GENERATED_RESOURCES_DIR = `${GENERATED_CODE_DIR}/resources`
/** Glob of all Honcho-generated resources */
export const GENERATED_RESOURCES_GLOB = `${GENERATED_RESOURCES_DIR}/*.{ts,tsx}`
/** Path to the generated file that re-exports the merged resource code */
export const RESOURCES_OUTPUT_FILE = `${GENERATED_CODE_DIR}/resources.ts`
